import Head from 'next/head'
// import Image from 'next/image'
import Script from 'next/script'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, huntingcoder blog, hunting coder" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* <Script src="/sc.js"
      strategy="lazyOnload">

      </Script> */}
      <main className={styles.main}>
          <img className={styles.myimg} src="/homeimg.avif" alt="home image"width={237} height={158} />
          {/* <Image className={styles.myimg} src="/homeimg.avif" width={237} height={158} alt='coding image' priority></Image> */}
          <h1 className={styles.title}>
          &lt;Huntingcoder/&gt; </h1>
          {/* <p className={styles.description}>A blog for huntingcoders for hunting coder Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloribus veniam vel in, neque doloremque perferendis esse itaque minus nobis nam dolor ipsum earum.</p> */}
          <div className={styles.blogs}>
            <h2>Popular blogs</h2>
            <div className={styles.blogitems}>
              <h3 className={styles.h3}>how to learn javascript in 2023?</h3>
              <p>javascriptis is a language learn to design logic</p>
            </div>
            <button className={styles.btn}>Read more</button>
          
          {/* <div className='blogs'> */}
            <div className={styles.blogitems}>
              <h3 className={styles.h3}>how to learn javascript in 2023?</h3>
              <p>javascriptis is a language learn to design logic</p>
            </div>
            <button className={styles.btn}>Read more</button>

          {/* </div> */}
          {/* <div className='blogs'> */}
            <div className={styles.blogitems}>
              <h3 className={styles.h3}>how to learn javascript in 2023?</h3>
              <p>javascriptis is a language learn to design logic</p>
            </div>
          {/* </div> */}
          <button className={styles.btn}>Read more</button>

          </div>
          
      </main>
      </>
  )
}
